### ISSUE TITLE
Que origem é essa?

### ISSUE THREAD

**Issue by danilobbezerra** [TBertuzzi/Correios.Pacotes#1]
Bertuzzi, valeu pela idéia, achei muito bacana, acabei caindo aqui sem querer pesquisando algo para rastreio de pacotes nos correios.
Vendo o projeto aqui me deparei com a url: http://sro.micropost.com.br/consulta.php?objetos={0}

Queria saber de onde é ela? porque não usar dos correios mesmo?

Valeu.

**Comment by TBertuzzi** [comment]
Essa URL é Interna dos Correios, pesquisando muito encontrei essa URL de APi interna deles. A atual pode mudar ou sair do ar.
